"""rename departmen

Revision ID: a15f97f8d153
Revises: 8c43fbe4e383
Create Date: 2024-05-14 13:53:18.481874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15f97f8d153'
down_revision = '8c43fbe4e383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
